name: E2E Test Automation

on:
  # Trigger on push to main/master branch
  push:
    branches: [ master, main ]

  # Trigger on pull requests
  pull_request:
    branches: [ master, main ]

  # Allow manual workflow dispatch
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - smoke
          - critical
          - e2e
          - regression

  # Scheduled runs (optional - runs daily at 2 AM UTC)
  # schedule:
  #   - cron: '0 2 * * *'

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run smoke tests
        if: github.event_name == 'pull_request' || github.event.inputs.test_suite == 'smoke'
        run: |
          pytest -m smoke -v --html=reports/smoke_report.html --self-contained-html
        env:
          BROWSER: chrome
          HEADLESS: true

      - name: Run critical tests
        if: github.event.inputs.test_suite == 'critical'
        run: |
          pytest -m critical -v --html=reports/critical_report.html --self-contained-html
        env:
          BROWSER: chrome
          HEADLESS: true

      - name: Run E2E tests
        if: github.event.inputs.test_suite == 'e2e'
        run: |
          pytest -m e2e -v --html=reports/e2e_report.html --self-contained-html
        env:
          BROWSER: chrome
          HEADLESS: true

      - name: Run regression suite
        if: github.event.inputs.test_suite == 'regression'
        run: |
          pytest -m regression -v --html=reports/regression_report.html --self-contained-html
        env:
          BROWSER: chrome
          HEADLESS: true

      - name: Run all tests
        if: github.event_name == 'push' || github.event.inputs.test_suite == 'all' || github.event_name == 'schedule'
        run: |
          pytest tests/ -v --html=reports/full_report.html --self-contained-html
        env:
          BROWSER: chrome
          HEADLESS: true

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-python-${{ matrix.python-version }}
          path: |
            reports/
            logs/
          retention-days: 30

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-screenshots-python-${{ matrix.python-version }}
          path: reports/**/screenshots/
          retention-days: 30

      - name: Test Summary
        if: always()
        run: |
          echo "## Test Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Python Version:** ${{ matrix.python-version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Browser:** Chrome (Headless)" >> $GITHUB_STEP_SUMMARY
          echo "- **Test Suite:** ${{ github.event.inputs.test_suite || 'all' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Trigger:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "View detailed reports in the artifacts section." >> $GITHUB_STEP_SUMMARY
